routes/web.php
<?php

use App\Http\Controllers\admin\AccountController;
use App\Http\Controllers\admin\ApiController;
use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\DepositController;
use App\Http\Controllers\admin\WithdrawController;
use App\Http\Controllers\Auth\PermissionsController;
use App\Http\Controllers\Auth\RolesController;
use App\Http\Controllers\Auth\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes([
    'register' => true
]);

//Route::post('/login',[LoginController::class,'process_login'])->name('login');
//Route::post('/logout',[LoginController::class ,'logout'])->name('logout');

Route::get('/', ['middleware' => 'auth', 'uses' => 'DashboardController@index']);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UsersController::class);

    Route::group(['prefix' => 'transaction'], function () {
        Route::resource('deposits', DepositController::class);
        Route::resource('withdraws', WithdrawController::class);
    });

    Route::group(['prefix' => 'account'], function () {
        Route::get('general_setting', [AccountController::class,'general_setting'])->name('general_setting');
        Route::get('change_password', [AccountController::class,'change_password'])->name('change_password');
        Route::patch('modify_general/{id}', [AccountController::class,'modify_general'])->name('modify_general');
        Route::patch('modify_password/{id}', [AccountController::class,'modify_password'])->name('modify_password');
    });

    Route::group(['prefix' => 'api'], function () {
        Route::get('api_keys', [ApiController::class,'api_keys'])->name('api_keys');
        Route::get('call_back', [ApiController::class,'call_back'])->name('call_back');
        Route::patch('modify_key/{id}', [ApiController::class,'modify_key'])->name('modify_key');
        Route::patch('modify_callback/{id}', [ApiController::class,'modify_callback'])->name('modify_callback');
    });


    Route::resource('roles', RolesController::class);
    Route::resource('permissions', PermissionsController::class);

});

resources/views/modals/deposit.blade.php
<div class="modal fade" id="modalassign" tabindex="-1" aria-labelledby="twoFactorAuthAppsTitle" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg two-factor-auth-apps modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="uploadFilesModalLabel">Deposit</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editUservForm" class="row gy-1 pt-75" method="POST" action="{{ route("deposits.store") }}">
                <div class="modal-body pb-5 px-sm-5 mx-50" >

                    {{ csrf_field() }}
                    @csrf
                    <h4>Initiate Deposit</h4>


                    <div class="mb-3">
                        <label class="form-label" for="modalEditUserFirstName">Phone Number</label>
                        <input value="" type="text" id="modalFirstName" name="phone" class="form-control" placeholder="Phone Number e.g 256771234567" data-msg="Please country" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="modalEditUserFirstName">Amount</label>
                        <input value="" type="number" id="modalFirstName" name="amount" class="form-control" placeholder="Amount" data-msg="Please country" />
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Initiate</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/modals/edit-loan-application.blade.php
<h1 class="text-center mb-2 pb-50" id="twoFactorAuthAppsTitle">Loan Application Details</h1>
{{--{{ route('clients.update', ['client' => $loan->id]) }}--}}
<form id="editUservForm" class="row gy-1 pt-75" method="POST" action="{{ route('requests.update', ['request' => $loans->id]) }}">
    {{ csrf_field() }}
    @csrf
    @method("PUT")
    <h4>Account Detail: <b>{{ $loans->client_info->account_names }}</b> ({{ $loans->client_info->account_number }})</h4>
    <h4>Borrowing Details</h4>
    <input hidden="" type="text" name="account_type" value="4" />

    <div class="col-12">
        <label class="form-label" for="modalEditUserFirstName">Business Details of the Applicant</label>
        <input value="{{ $loans->loan_application_data->type_of_business }}" type="text" id="modalFirstName" name="business_details" class="form-control" placeholder="Business Details of the Applicant" data-msg="Please enter your first name" />
    </div>
    <div class="col-12">
        <label class="form-label" for="modalEditUserLastName">Purpose for borrowing</label>
        <input value="{{ $loans->loan_application_data->purpose_of_loan }}" type="text" id="modalEditUserFirstName" name="purpose_of_business" class="form-control" placeholder="Purpose for borrowing" data-msg="Please enter your first name" />
    </div>

    <h4>Loan Details</h4>


    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserLastName">Type of Loan</label>
       <select name="type_of_loan" class="form-control" id="">
            @foreach($loans_types as $data)
                <option  value={{ $data->id == $loans->loan_application_data->type_of_business ? $loans->loan_application_data->type_of_business  : $data->id }}> {{ $data->id == $loans->loan_application_data->type_of_business ? $data->name : $data->name }} </option>
            @endforeach

        </select>
    </div>

    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserFirstName">Period Category (Daily, Weekly, Monthly)</label>
        <select id="" name="period_type" class="form-select" aria-label="Default select example">
            <option value="{{ $loans->loan_type }}">{{ $loans->loan_type }}</option>
            <option value="Daily">Daily</option>
            <option value="Weekly">Weekly</option>
            <option value="Monthly">Monthly</option>
        </select>
    </div>

    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserFirstName">Amount Requested</label>
        <input value="{{ $loans->amount_requested }}" type="number" id="" name="amount_requested" class="form-control" placeholder="Amount Requested" data-msg="Please enter your first name" />
    </div>
    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserLastName">Duration</label>
        <input value="{{ $loans->loan_period }}" type="number" id="" name="duration" class="form-control" placeholder="Duration" data-msg="Please enter your first name" />
    </div>

    <div class="col-12">
        <label class="form-label" for="modalEditUserLastName">Disbursement date</label>
        <input value={{ $loans->requested_date }}"" type="date" id="" name="disburse_date" class="form-control" placeholder="Disbursement date" data-msg="Please enter your first name" />
    </div>


    <h4>Guarantor Details</h4>

    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserLastName">Guarantor 1</label>
        <input value="{{ $loans->loan_application_data->guarantor_one }}" type="text" id="" name="guarantor1" class="form-control" placeholder="Guarantor 1" data-msg="Please enter your first name" />
    </div>

    <div class="col-12 col-md-6">
        <label class="form-label" for="modalEditUserFirstName">Guarantor 2</label>
        <input value="{{ $loans->loan_application_data->guarantor_two }}" type="text" id="" name="guarantor2" class="form-control" placeholder="Guarantor 2" data-msg="Please enter your first name" />
    </div>

    <div class="col-12 text-center mt-2 pt-50">
        <button type="submit" class="btn btn-primary me-1">Submit</button>
        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">Discard</button>
    </div>
</form>

resources/views/modals/modal-deposit.blade.php
<!-- edit individual apps modal -->
<div class="modal fade" id="depositModal" tabindex="-1" aria-labelledby="twoFactorAuthAppsTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg two-factor-auth-apps modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pb-5 px-sm-5 mx-50" id="edit-individual-account-modal-content">


      </div>
    </div>
  </div>
</div>

resources/views/modals/modal-edit-account.blade.php
<!-- edit individual apps modal -->
<div class="modal fade" id="editIndividualAccountModel" tabindex="-1" aria-labelledby="twoFactorAuthAppsTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg two-factor-auth-apps modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pb-5 px-sm-5 mx-50" id="edit-individual-account-modal-content">


      </div>
    </div>
  </div>
</div>

resources/views/modals/modal-withdraw.blade.php
<!-- edit individual apps modal -->

<div class="modal fade" id="withdrawModal" tabindex="-1" aria-labelledby="twoFactorAuthAppsTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm two-factor-auth-apps modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-transparent">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body pb-5 px-sm-5 mx-50" id="edit-individual-account-modal-content">

          <h2 class="text-center mb-2 pb-50" id="twoFactorAuthAppsTitle"><b>Withdraw Funds</b></h2>
          <center><h2 class="modal-title" id="exampleModalLabel"><span id="accountbal">Bal: UGX {{ number_format($user->balance) }}</span></h2></center>
          <label class="form-label" for="basic-icon-default-fullname">Withdraw:</label>
          <h4 class="modal-title" id="">Charge: <span id="chargeamount">0</span></h4>
          <h4 class="modal-title" id="">Total: <span id="totalamount">0</span></h4>

          <form method="POST" action="{{ route("withdraws.store") }}">
              {{ csrf_field() }}
              @csrf

              <div class="row">
                  <div class="col-12">
                      <div class="mb-1">
                          <label class="form-label" for="basic-icon-default-fullname">Withdraw Amount</label>
                          <input onkeyup="generateWithdrawFees()" type="number" name="amount" class="form-control dt-full-name" id="amountwithdraw" placeholder="Amount e.g 1000" aria-label="Amount e.g 1000" />
                      </div>
                  </div>

                  <div class="col-12">
                      <div class="mb-1">
                          <label class="form-label" for="basic-icon-default-post">Mobile Money</label>
                          <input type="tel" id="mobilenumber" name="phone" class="form-control dt-post" placeholder="Mobile Money Number e.g +256772000000" aria-label="Mobile Money Number e.g 256772000000" />
                      </div>
                  </div>

                  <div class="col-12 text-center mt-2 pt-50">
                      <button id="savebutwithdraw" type="submit" class="btn btn-warning me-1">Submit Withdraw</button>
                  </div>
              </div>
          </form>

      </div>
    </div>
  </div>
</div>