routes/web.php
<?php

use App\Http\Controllers\admin\AccountController;
use App\Http\Controllers\admin\ApiController;
use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\DepositController;
use App\Http\Controllers\admin\WithdrawController;
use App\Http\Controllers\Auth\PermissionsController;
use App\Http\Controllers\Auth\RolesController;
use App\Http\Controllers\Auth\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes([
    'register' => true
]);

//Route::post('/login',[LoginController::class,'process_login'])->name('login');
//Route::post('/logout',[LoginController::class ,'logout'])->name('logout');

Route::get('/', ['middleware' => 'auth', 'uses' => 'DashboardController@index']);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UsersController::class);

    Route::group(['prefix' => 'transaction'], function () {
        Route::resource('deposits', DepositController::class);
        Route::resource('withdraws', WithdrawController::class);
    });

    Route::group(['prefix' => 'account'], function () {
        Route::get('general_setting', [AccountController::class,'general_setting'])->name('general_setting');
        Route::get('change_password', [AccountController::class,'change_password'])->name('change_password');
        Route::patch('modify_general/{id}', [AccountController::class,'modify_general'])->name('modify_general');
        Route::patch('modify_password/{id}', [AccountController::class,'modify_password'])->name('modify_password');
    });

    Route::group(['prefix' => 'api'], function () {
        Route::get('api_keys', [ApiController::class,'api_keys'])->name('api_keys');
        Route::get('call_back', [ApiController::class,'call_back'])->name('call_back');
        Route::patch('modify_key/{id}', [ApiController::class,'modify_key'])->name('modify_key');
        Route::patch('modify_callback/{id}', [ApiController::class,'modify_callback'])->name('modify_callback');
    });


    Route::resource('roles', RolesController::class);
    Route::resource('permissions', PermissionsController::class);

});

resources/views/roles/create.blade.php
@extends('content.main')

@section('title', 'New Produce | Management')
@push('styles')
{{--    <link rel="stylesheet" href="{{ asset('assets/vendor/tom-select/dist/css/tom-select.bootstrap5.css') }}">--}}
@endpush
@section('content')
    <div class="content container-fluid">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row align-items-end">
          <div class="col-sm mb-2 mb-sm-0">

            <h1 class="page-header-title"> Add new role and assign permissions.</h1>
          </div>
          <!-- End Col -->

          <div class="col-auto">
            <a class="btn btn-primary" href="{{ url()->previous() }}">
              <i class="bi-backspace me-1"></i> Back
            </a>
          </div>
          <!-- End Col -->
        </div>
        <!-- End Row -->
      </div>
      <!-- End Page Header -->


        <div class="row">
            <div class="col-lg-12">
                <div class="card card-info">
                    <div class="card-body">
                        <div class="bg-light p-4 rounded">
                            <div class="container mt-4">

                                @if (count($errors) > 0)
                                    <div class="alert alert-danger">
                                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif

                                <form method="POST" action="{{ route('roles.store') }}">
                                    @csrf
                                    <div class="mb-3">
                                        <label for="name" class="form-label">Name</label>
                                        <input value="{{ old('name') }}"
                                               type="text"
                                               class="form-control"
                                               name="name"
                                               placeholder="Name" required>
                                    </div>

                                    <label for="permissions" class="form-label">Assign Permissions</label>

                                    <table class="table table-striped">
                                        <thead>
                                        <th scope="col" width="1%"><input type="checkbox" name="all_permission"></th>
                                        <th scope="col" width="20%">Name</th>
                                        <th scope="col" width="1%">Guard</th>
                                        </thead>

                                        @foreach($permissions as $permission)
                                            <tr>
                                                <td>
                                                    <input type="checkbox"
                                                           name="permission[{{ $permission->name }}]"
                                                           value="{{ $permission->name }}"
                                                           class='permission'>
                                                </td>
                                                <td>{{ $permission->name }}</td>
                                                <td>{{ $permission->guard_name }}</td>
                                            </tr>
                                        @endforeach
                                    </table>

                                    <button type="submit" class="btn btn-primary">Save user</button>
                                    <a href="{{ route('users.index') }}" class="btn btn-default">Back</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection



@push('scripts')
    <script src="{{ asset('assets/vendor/tom-select/dist/js/tom-select.complete.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net.extensions/select/select.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/pdfmake/build/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/tom-select/dist/js/tom-select.complete.min.js') }}"></script>


  <script>
      $(document).ready(function() {
          $('[name="all_permission"]').on('click', function() {

              if($(this).is(':checked')) {
                  $.each($('.permission'), function() {
                      $(this).prop('checked',true);
                  });
              } else {
                  $.each($('.permission'), function() {
                      $(this).prop('checked',false);
                  });
              }

          });
      });
    (function() {
      window.onload = function () {

          HSCore.components.HSTomSelect.init('.js-select')
        // INITIALIZATION OF NAVBAR VERTICAL ASIDE
        // =======================================================
        new HSSideNav('.js-navbar-vertical-aside').init()




        // INITIALIZATION OF FORM SEARCH
        // =======================================================
        new HSFormSearch('.js-form-search')


        // INITIALIZATION OF BOOTSTRAP DROPDOWN
        // =======================================================
        HSBsDropdown.init()


        // INITIALIZATION OF NAV SCROLLER
        // =======================================================
        new HsNavScroller('.js-nav-scroller')


        // INITIALIZATION OF DROPZONE
        // =======================================================
        HSCore.components.HSDropzone.init('.js-dropzone')
      }
    })()
  </script>

  <script>
      (function () {
        // STYLE SWITCHER
        // =======================================================
        const $dropdownBtn = document.getElementById('selectThemeDropdown') // Dropdowon trigger
        const $variants = document.querySelectorAll(`[aria-labelledby="selectThemeDropdown"] [data-icon]`) // All items of the dropdown

        // Function to set active style in the dorpdown menu and set icon for dropdown trigger
        const setActiveStyle = function () {
          $variants.forEach($item => {
            if ($item.getAttribute('data-value') === HSThemeAppearance.getOriginalAppearance()) {
              $dropdownBtn.innerHTML = `<i class="${$item.getAttribute('data-icon')}" />`
              return $item.classList.add('active')
            }

            $item.classList.remove('active')
          })
        }

        // Add a click event to all items of the dropdown to set the style
        $variants.forEach(function ($item) {
          $item.addEventListener('click', function () {
            HSThemeAppearance.setAppearance($item.getAttribute('data-value'))
          })
        })

        // Call the setActiveStyle on load page
        setActiveStyle()

        // Add event listener on change style to call the setActiveStyle function
        window.addEventListener('on-hs-appearance-change', function () {
          setActiveStyle()
        })
      })()
    </script>
@endpush

resources/views/roles/edit.blade.php
@extends('content.main')

@section('title', 'Edit Produce')
@push('styles')
{{--    <link rel="stylesheet" href="{{ asset('assets/vendor/tom-select/dist/css/tom-select.bootstrap5.css') }}">--}}
@endpush
@section('content')
    <div class="content container-fluid">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row align-items-end">
          <div class="col-sm mb-2 mb-sm-0">
                <h1 class="page-header-title"> Edit User Role</h1>
          </div>
          <!-- End Col -->

          <div class="col-auto">
                <a class="btn btn-primary" href="{{ url()->previous() }}" >
                    <i class="bi-backspace me-1"></i> Back
                </a>
          </div>
          <!-- End Col -->
        </div>
        <!-- End Row -->
      </div>
      <!-- End Page Header -->


        <div class="row">
            <div class="col-lg-12">
                <div class="card card-info">
                    <div class="card-body">
                        <form method="POST" action="{{ route('roles.update', $role->id) }}">
                            @method('patch')
                        @csrf
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input value="{{ $role->name }}"
                                   type="text"
                                   class="form-control"
                                   name="name"
                                   placeholder="Name" required>
                        </div>

                        <label for="permissions" class="form-label">Assign Permissions</label>

                        <table class="table table-striped">
                            <thead>
                            <th scope="col" width="1%"><input type="checkbox" name="all_permission"></th>
                            <th scope="col" width="20%">Name</th>
                            <th scope="col" width="1%">Guard</th>
                            </thead>

                            @foreach($permissions as $permission)
                                <tr>
                                    <td>
                                        <input type="checkbox"  name="permission[{{ $permission->name }}]" value="{{ $permission->name }}"  class='permission' {{ in_array($permission->name, $rolePermissions) ? 'checked': '' }}>
                                    </td>
                                    <td>{{ $permission->name }}</td>
                                    <td>{{ $permission->guard_name }}</td>
                                </tr>
                            @endforeach
                        </table>

                        <button type="submit" class="btn btn-primary">Save changes</button>
                        <a href="{{ route('roles.index') }}" class="btn btn-default">Back</a>
                        </form>
                    </div>

                </div>
                </div>
            </div>
        </div>


    <!-- End Content -->
@endsection



@push('scripts')
    <script src="{{ asset('assets/vendor/tom-select/dist/js/tom-select.complete.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net.extensions/select/select.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/pdfmake/build/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/tom-select/dist/js/tom-select.complete.min.js') }}"></script>


  <script>
    $(document).ready(function() {
          $('[name="all_permission"]').on('click', function() {

              if($(this).is(':checked')) {
                  $.each($('.permission'), function() {
                      $(this).prop('checked',true);
                  });
              } else {
                  $.each($('.permission'), function() {
                      $(this).prop('checked',false);
                  });
              }

          });
      });
    (function() {
      window.onload = function () {

          HSCore.components.HSTomSelect.init('.js-select')
        // INITIALIZATION OF NAVBAR VERTICAL ASIDE
        // =======================================================
        new HSSideNav('.js-navbar-vertical-aside').init()

        // INITIALIZATION OF FORM SEARCH
        // =======================================================
        new HSFormSearch('.js-form-search')

        // INITIALIZATION OF BOOTSTRAP DROPDOWN
        // =======================================================
         HSBsDropdown.init()

        // INITIALIZATION OF NAV SCROLLER
        // =======================================================
        new HsNavScroller('.js-nav-scroller')

        // INITIALIZATION OF DROPZONE
        // =======================================================
         HSCore.components.HSDropzone.init('.js-dropzone')
      }
    })()
  </script>

  <script>
      (function () {
            // STYLE SWITCHER
            // =======================================================
            const $dropdownBtn = document.getElementById('selectThemeDropdown') // Dropdowon trigger
            const $variants = document.querySelectorAll(`[aria-labelledby="selectThemeDropdown"] [data-icon]`) // All items of the dropdown

            // Function to set active style in the dorpdown menu and set icon for dropdown trigger
            const setActiveStyle = function () {
              $variants.forEach($item => {
                if ($item.getAttribute('data-value') === HSThemeAppearance.getOriginalAppearance()) {
                  $dropdownBtn.innerHTML = `<i class="${$item.getAttribute('data-icon')}" />`
                  return $item.classList.add('active')
                }

                $item.classList.remove('active')
              })
            }

            // Add a click event to all items of the dropdown to set the style
            $variants.forEach(function ($item) {
              $item.addEventListener('click', function () {
                HSThemeAppearance.setAppearance($item.getAttribute('data-value'))
              })
            })

            // Call the setActiveStyle on load page
            setActiveStyle()

            // Add event listener on change style to call the setActiveStyle function
            window.addEventListener('on-hs-appearance-change', function () {
          setActiveStyle()
        })
      })()
    </script>
@endpush